#!/bin/sh
start() {
        export DISPLAY=:0
        PARAM="-sync -name Ubuntu-xfce4"
        if [ ! -z $SCREEN ]
        then
          PARAM="-screen $SCREEN $PARAM"
        else
          PARAM="-screen 1280x720 $PARAM"
        fi
        if [ ! -z $FULLSCREEN ] && [ -z $SCREEN ]
        then 
         PARAM="-fullscreen $PARAM"
        fi
        su -p  -c "/usr/bin/Xephyr $PARAM :10" user
}

case $1 in
  start)
    start
  ;;
  *)
      echo "[?] Use ./Xephyr [start]"
  ;;
esac
